name: Defining Outputs Intro

on:
  workflow_dispatch:
  # push:

jobs:
    job1:
      runs-on: ubuntu-latest
      outputs:
        output1: ${{ steps.step1.outputs.test }}
        output2: ${{ steps.step2.outputs.test }}
        output3: ${{ steps.findfile.outputs.diff }}
        output4: ${{ steps.findfile.outputs.addedFiles }}
      steps:
        - id: step1
          run: echo "test=hello" >> $GITHUB_OUTPUT
        - id: step2
          run: echo "test=${{ github.actor }}" >> $GITHUB_OUTPUT
        - id: findfile
          run: |
            # Save the output of git diff to a variable
            diff=$(git diff)
            echo "Diff: $diff"
            echo "diff=$diff" >> $GITHUB_OUTPUT
            # Loop through each line of diff and add the name of added files to addedFiles
            addedFiles=""
            while read -r line; do
              if [[ $line == +* ]]; then
                addedFiles="$addedFiles $line"
              fi
            done <<< "$diff"
            # check addedFiles not empty
            if [ -n "$addedFiles" ]; then
              echo "addedFiles=$addedFiles" >> $GITHUB_OUTPUT
            fi
    job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - env:
            OUTPUT1: ${{needs.job1.outputs.output1}}
            OUTPUT2: ${{needs.job1.outputs.output2}}
            OUTPUT3: ${{needs.job1.outputs.output3}}
            OUTPUT4: ${{needs.job1.outputs.output4}}
          run: |
            echo "$OUTPUT1 $OUTPUT2!"
            echo "Added files: $OUTPUT3 $OUTPUT4"