name: Deploy Storage Account
on:
    workflow_dispatch:
    # push:
    #     paths:
    #         - 'storage_accounts/**'

permissions: write-all

jobs:
    job1:
        name: Set outputs in PowerShell script
        runs-on: windows-latest
        outputs:
            output1: ${{ steps.step1.outputs.test }}
            output2: ${{ steps.step2.outputs.test }}
        steps:
            - id: step1
              shell: pwsh
              run: echo "test=hello" >> "$GITHUB_OUTPUT"
            - id: step2
              shell: pwsh
              run: echo "test=hello" >> $env:GITHUB_OUTPUT

    job2:
        name: Print outputs in PowerShell script
        needs: job1
        runs-on: windows-latest
        steps:     
        - env:
            OUTPUT1: ${{needs.job1.outputs.output1}}
            OUTPUT2: ${{needs.job1.outputs.output2}}
          run: echo "$OUTPUT1 $OUTPUT2"