name: Deploy Storage Account
on:
    push:
        paths:
            - 'storage_accounts/**'

permissions: write-all

jobs:
    job1:
        name: Set outputs in PowerShell script
        runs-on: windows-latest
        outputs:
            fileName: ${{ steps.findfile.outputs.fileName }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0 # Fetches the commit history to compare changes

            - id: findfile
              shell: pwsh
              run: |
                # Save the output of git diff to a variable
                $diffOutput = git diff --name-only HEAD HEAD~1
                echo "Diff Output: $diffOutput"
                
                $addedFiles = @()
            
                # Loop through each line of diffOutput
                foreach ($line in $diffOutput -split "`n") {
                if ($line -match 'storage_accounts/') {
                    $addedFiles += $line
                }
                }
                echo "Added Files: $addedFiles"

                # Check if addedFiles is not empty
                if ($addedFiles.Count -gt 0) {
                $fileName = $addedFiles -join ', '
                echo "File Name: $fileName"
                echo "fileName=$fileName" >> $GITHUB_OUTPUT
                } else {
                echo "No new files in 'storage_accounts/'"
                }

    job2:
        name: Print outputs in PowerShell script
        needs: job1
        runs-on: windows-latest
        steps:     
            - env:
                # CLIENT_ID: ${{ secrets.CLIENT_ID }}
                # CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                # SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
                # TENANT_ID: ${{ secrets.TENANT_ID }}
                FILE_NAME: ${{ needs.job1.outputs.fileName }}
              shell: pwsh
              run: |
                echo "File Name: $FILE_NAME"