name: Deploy Storage Account
on:
    workflow_dispatch:
    # push:
    #     paths:
    #         - 'storage_accounts/**'

permissions: write-all

jobs:
    job1:
        name: Set outputs in PowerShell script
        runs-on: windows-latest
        outputs:
            output1: ${{ steps.findfile.outputs.changedFiles }}
            output2: ${{ steps.control.outputs.changedFilesTest }}
        steps:
            - id: findfile
              shell: pwsh
              run: |
                echo "changedFiles=${{ github.actor }}" >> "$GITHUB_OUTPUT"
            - id: control
              shell: pwsh
              run: |
                echo "changedFilesTest=${{ github.actor }}" > $env:GITHUB_OUTPUT

    job2:
        name: Print outputs in PowerShell script
        needs: job1
        runs-on: windows-latest
        steps:     
            - env:
                CHANGED_FILES: ${{ needs.job1.outputs.output1 }}
                TEST_CONTROL: ${{ needs.job1.outputs.output2 }}
              shell: pwsh
              run: |
                echo "Changed files: $CHANGED_FILES"
                echo "Test control: $TEST_CONTROL"