name: Deploy Storage Account
on:
    push:
        paths:
            - 'storage_accounts/**'

permissions: write-all

jobs:
    job1:
        name: Set outputs in PowerShell script
        runs-on: windows-latest
        outputs:
            output1: ${{ steps.findfile.outputs.changedFiles }}
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - id: findfile
              shell: pwsh
              run: |
                $outputValue = "Your output value"
                echo "::set-output name=changedFiles::$outputValue"

    job2:
        name: Print outputs in PowerShell script
        needs: job1
        runs-on: windows-latest
        steps:     
            - env:
                # CLIENT_ID: ${{ secrets.CLIENT_ID }}
                # CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                # SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
                # TENANT_ID: ${{ secrets.TENANT_ID }}
                CHANGED_FILES: ${{ needs.job1.outputs.output1 }}
              shell: pwsh
              run: |
                echo "Changed files: $CHANGED_FILES"